### ISSUE TITLE
Create tagged releases

### ISSUE THREAD

**Issue by PanderMusubi** [De7vID/klingon-assistant-data#273]
Like https://github.com/De7vID/klingon-assistant-android/releases, please create also tagged releases for klingon-assistant-data. This helps e.g. also https://github.com/PanderMusubi/klingon

PS   For those interested, here are DEB packages for Klingon word list and spell checker https://github.com/PanderMusubi/klingon/tree/master/packages

**Comment by De7vID** [comment]
Done: https://github.com/De7vID/klingon-assistant-data/releases

**Comment by PanderMusubi** [comment]
Thanks, next release will use the version number from the tagged release. Meanwhile, vote for or spread the word for:
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911172
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911173
* https://bugs.launchpad.net/ubuntu/+bug/1798178 (needs login to vote)
* https://bugs.launchpad.net/ubuntu/+bug/1798179 (needs login to vote)
