### ISSUE TITLE
Sentence type "bc" - not explained

### ISSUE THREAD

**Issue by Cyberman-tM** [De7vID/klingon-assistant-data#317]
Example:
       <column name="entry_name">SoH 'Iv?</column>
      <column name="part_of_speech">sen:bc</column>

"bc" is never explained, should be in the header XML, I think.

Apparently it means "Beginner's Conversation"?

**Comment by De7vID** [comment]
Yes, that's what it means. I just forgot to add that explanation to the header file when I tagged those sentences. Thanks.
