### ISSUE TITLE
Font severely distorted on iOS 14

### ISSUE THREAD

**Issue by kechpaja** [De7vID/klingon-assistant-data#430]
There isn't much to say other than what's clearly visible in this screenshot: 

![image](https://user-images.githubusercontent.com/1562757/97916236-6180ea00-1d5b-11eb-9e64-f8d270cd75e0.png)

The same sort of distortion/terrible kerning is visible when typing search terms.

**Comment by De7vID** [comment]
This is the wrong repo (as it's not a data issue). This issue (https://github.com/dadap/flingon-assister/issues/32) has already been reported against the iOS codebase.

**Comment by De7vID** [comment]
Thanks for the report, I think @dadap is already working on this.
